"""auto

Revision ID: 08ffdf2a74d7
Revises: 3b4648330a43
Create Date: 2022-05-24 23:23:31.583606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ffdf2a74d7'
down_revision = '3b4648330a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
