"""auto

Revision ID: 25389758479a
Revises: 08ffdf2a74d7
Create Date: 2022-05-24 23:26:54.204033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25389758479a'
down_revision = '08ffdf2a74d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
