"""auto

Revision ID: 3b4648330a43
Revises: 73f3825082bc
Create Date: 2022-05-24 23:18:10.098511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4648330a43'
down_revision = '73f3825082bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
