"""auto

Revision ID: 73f3825082bc
Revises: 72fd169b41c5
Create Date: 2022-05-24 20:44:39.075086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f3825082bc'
down_revision = '72fd169b41c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
