"""auto

Revision ID: e486bdd0b8f0
Revises: 0153e46344f3
Create Date: 2022-05-24 23:37:35.117313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e486bdd0b8f0"
down_revision = "0153e46344f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("todos", "importance", sa.CheckConstraint("importance<4"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
